### ISSUE TITLE
Problem compiling silc 1.1.10 on openSuSE 12.2: Bad value collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by Chewie9999** [silc/silc#1]
I tried compiling the latest version on openSuSE 12.2 with the following command line:

./configure --with-silc-plugin=/usr/lib64/irssi --enable-ipv6 --sbindir=/sbin -sysconfdir=/etc --mandir=/usr/share/man --bindir=/bin --localstatedir=/var --prefix=/usr

This completed with the following output:

Building text frontend ..... : yes, using termcap
Building irssi bot ......... : no
Building irssi proxy ....... : no
Building with IPv6 support . : yes
Building with module support : yes
Building with Perl support . : static (in irssi binary)
Perl library directory ..... : /usr/lib/perl5/5.16.0/x86_64-linux-thread-multi
- NOTE: This was automatically set to the same directory you gave with
  --prefix. If you want the perl libraries to install to their 'correct'
  path, you'll need to give --with-perl-lib=site option to configure.
  Anyway, installing perl to this directory should work just as well.
  Install prefix ............. : /usr

If there was any problems, read the INSTALL file.
## silc-client Configuration Summary:

 Target host ...................: x86_64-unknown-linux-gnu
 Compiler ......................: gcc
 CFLAGS ........................: -D_GNU_SOURCE -g -Wall -finline-functions -Wno-pointer-sign -O2 -D_REENTRANT
 LDFLAGS .......................: -L$(silc_top_srcdir)/lib
 LIBS ..........................:  -lpthread

 Installation prefix ...........: /usr
 bin directory .................: /bin
 sbin directory ................: /sbin
 etc directory .................: /etc
 man directory .................: /usr/share/man
 doc directory .................: /usr/share/doc/silc-client
 include directory .............: /usr/include

 Compile SILC Client ...........: yes
 IPv6 support ..................: yes
 Iconv support .................: yes
 Assembler optimizations .......: yes
 Multi-threads support .........: yes
 Debugging enabled .............: no

Compile the sources with 'make' or 'gmake' command.

After running make, I get the following error:
/bin/sh ../../../libtool  --tag=CC   --mode=link gcc  -g -O2 -Wall   -o libsilc_core.la -rpath /usr/lib64/irssi/modules clientutil.lo silc-c
hannels.lo silc-core.lo silc-nicklist.lo silc-queries.lo silc-servers.lo silc-expandos.lo silc-servers-reconnect.lo silc-lag.lo silc-chatnet
s.lo silc-cmdqueue.lo client_ops.lo ../../../../../lib/libsilc.la ../../../../../lib/libsilcclient.la
libtool: link: gcc -shared  -fPIC -DPIC  .libs/clientutil.o .libs/silc-channels.o .libs/silc-core.o .libs/silc-nicklist.o .libs/silc-queries
.o .libs/silc-servers.o .libs/silc-expandos.o .libs/silc-servers-reconnect.o .libs/silc-lag.o .libs/silc-chatnets.o .libs/silc-cmdqueue.o .l
ibs/client_ops.o  -Wl,--whole-archive ../../../../../lib/.libs/libsilc.a ../../../../../lib/.libs/libsilcclient.a -Wl,--no-whole-archive  -L
/tmp/silc-client-1.1.10/lib -lpthread  -O2   -Wl,-soname -Wl,libsilc_core.so.0 -o .libs/libsilc_core.so.0.0.0
/usr/lib64/gcc/x86_64-suse-linux/4.7/../../../../x86_64-suse-linux/bin/ld: ../../../../../lib/.libs/libsilc.a(stringprep.o): relocation R_X8
6_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
../../../../../lib/.libs/libsilc.a(stringprep.o): could not read symbols: Bad value
collect2: error: ld returned 1 exit status
make[7]: *** [libsilc_core.la] Error 1
make[7]: Leaving directory`/tmp/silc-client-1.1.10/apps/irssi/src/silc/core'
make[6]: **\* [all-recursive] Error 1
make[6]: Leaving directory `/tmp/silc-client-1.1.10/apps/irssi/src/silc'
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory`/tmp/silc-client-1.1.10/apps/irssi/src'
make[4]: **\* [all-recursive] Error 1
make[4]: Leaving directory `/tmp/silc-client-1.1.10/apps/irssi'
make[3]: *** [all] Error 2
make[3]: Leaving directory`/tmp/silc-client-1.1.10/apps/irssi'
make[2]: **\* [all-recursive] Error 1
make[2]: Leaving directory `/tmp/silc-client-1.1.10/apps'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/tmp/silc-client-1.1.10'
make: **\* [all] Error 2

I can provide more logs if required.
Is there something missing from my irssi install?
If I run configure without the "--with-silc-plugin=/usr/lib64/irssi", it compiles successfully.
irssi is version 0.8.15 (which comes with openSuSE).

Thank you,

Chewie

**Comment by Chewie9999** [comment]
I've just compiled and installed irssi 0.16rc1 with the following command:

./configure --sbindir=/sbin --sysconfdir=/etc --mandir=/usr/share/man --bindir=/usr/bin --localstatedir=/var --prefix=/usr --with-bot --with-proxy

and that comes up with the same errors.

**Comment by priikone** [comment]
On Fri, 9 May 2014, Chewie wrote:

> After running make, I get the following error:
> /bin/sh ../../../libtool  --tag=CC   --mode=link gcc  -g -O2 -Wall   -o libsilc_core.la -rpath /usr/lib64/irssi/modules clientutil.lo silc-c
> hannels.lo silc-core.lo silc-nicklist.lo silc-queries.lo silc-servers.lo silc-expandos.lo silc-servers-reconnect.lo silc-lag.lo silc-chatnet
> s.lo silc-cmdqueue.lo client_ops.lo ../../../../../lib/libsilc.la ../../../../../lib/libsilcclient.la
> libtool: link: gcc -shared  -fPIC -DPIC  .libs/clientutil.o .libs/silc-channels.o .libs/silc-core.o .libs/silc-nicklist.o .libs/silc-queries
> .o .libs/silc-servers.o .libs/silc-expandos.o .libs/silc-servers-reconnect.o .libs/silc-lag.o .libs/silc-chatnets.o .libs/silc-cmdqueue.o .l
> ibs/client_ops.o  -Wl,--whole-archive ../../../../../lib/.libs/libsilc.a ../../../../../lib/.libs/libsilcclient.a -Wl,--no-whole-archive  -L
> /tmp/silc-client-1.1.10/lib -lpthread  -O2   -Wl,-soname -Wl,libsilc_core.so.0 -o .libs/libsilc_core.so.0.0.0
> /usr/lib64/gcc/x86_64-suse-linux/4.7/../../../../x86_64-suse-linux/bin/ld: ../../../../../lib/.libs/libsilc.a(stringprep.o): relocation R_X8
> 6_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
> ../../../../../lib/.libs/libsilc.a(stringprep.o): could not read symbols: Bad value
> collect2: error: ld returned 1 exit status
> make[7]: **\* [libsilc_core.la] Error 1
> 
> I'm not sure if the current SILC Plugin works with Irssi 0.8.15, I'll have 
> to test it a bit later.  However, please read the README.PLUGIN in the 
> silc-client package and try some of the options it suggests.  In addition 
> to the options it suggest you could also try --enable-shared and if that 
> doesn't help then --disable-shared --enable-static.

I hope to fix any of the Irssi compatibility issues to next version.

```
Pekka
```

**Comment by Chewie9999** [comment]
Thanks Pekka,
Both choices result in the compilation completing successfully.
"--enable-shared" creates the .so file required for irssi.
Yes, I don't think it works in 0.8.15 - after running "/load silc" in irssi, i get the following:
Error loading module silc/core: /usr/lib64/irssi/modules/libsilc_core.so: undefined symbol: silc_default_hash
Loaded module silc/fe
Loaded module silc/fe_common

I will wait for the new version.
Thank you very much for your quick reply!

**Comment by priikone** [comment]
SILC Client 1.1.11 released.  I tested plugin with Fedora 20 and Irssi 0.8.16-rc1 successfully.
