### ISSUE TITLE
configure.in missing ?

### ISSUE THREAD

**Issue by danhimalplanet** [silc/silc#2]
Is there a missing configure.in file at top level?

**Comment by priikone** [comment]
On Tue, 13 May 2014, danhimalplanet wrote:

> Is there a missing configure.in file at top level?
> 
> To what tree are you referring to?   All official packages have 
> configure.ac.

```
Pekka
```

**Comment by danhimalplanet** [comment]
I'm interested in compiling the irssi silc plugin.

I don't see an autogen script at top level.  the INSTALL file at top level says to run ./configure ( there is no ./configure )

Is this the wrong tree to use to compile the irssi plugin ?

**Comment by priikone** [comment]
On Wed, 14 May 2014, danhimalplanet wrote:

> I'm interested in compiling the irssi silc plugin.
> 
> I don't see an autogen script at top level.  the INSTALL file at top 
> level says to run ./configure ( there is no ./configure )
> 
> Is this the wrong tree to use to compile the irssi plugin ?
> 
> If you want to compile directly from GIT tree, notice the tree doesn't 
> have the configure script, it would have to be generated with Autodist. 
> Read the README.GIT.

But easiest way is to simply download the silc-client package and follow 
the instructions in README.PLUGIN: http://silcnet.org/client.html

```
Pekka
```

**Comment by danhimalplanet** [comment]
I tried building the irssi silc plugin from the source located at http://silcnet.org/client.html ,
I couldn't get irssi-0.8.15-5 to load the plugin correctly. 

there is no configure.ac or configure.in in the directory silc/apps/autodist/

**Comment by priikone** [comment]
On Wed, 14 May 2014, danhimalplanet wrote:

> I tried building the irssi silc plugin from the source located at http://silcnet.org/client.html ,
> I couldn't get irssi-0.8.15-5 to load the plugin correctly.
> 
> I have tested plugin only with 0.8.16-rc1.  Most problems are related to 
> things being installed in wrong places, so refer to the instructions in 
> README.PLUGIN.
> 
> there is no configure.ac or configure.in in the directory silc/apps/autodist/
> 
> Autodist is compiled like any other normal source package. Unpack the 
> autodist-1.5.tar.gz and then:

```
./configure
make
make install

Pekka
```

**Comment by danhimalplanet** [comment]
after running
git clone https://github.com/silc/silc
autodist client
automake --add-missing
autodist client

[fpm@facepalm]~/src/silc% ./configure --prefix=/usr --with-silc-plugin  --without-silc-includes --enable-shared 1>/dev/null  
/bin/grep: no/silc.h: No such file or directory
/bin/grep: no/silc.h: No such file or directory
config.status: WARNING:  'apps/irssi/Makefile.defines_int.in' seems to ignore the --datarootdir setting
config.status: WARNING:  'Makefile.defines_int.in' seems to ignore the --datarootdir setting
[fpm@facepalm]~/src/silc% 
[fpm@facepalm]~/src/silc% ./configure --prefix=/usr --with-silc-plugin=/usr/lib64/irssi --without-silc-includes --enable-shared 1>/dev/null  
/bin/grep: no/silc.h: No such file or directory
/bin/grep: no/silc.h: No such file or directory
config.status: WARNING:  'apps/irssi/Makefile.defines_int.in' seems to ignore the --datarootdir setting
config.status: WARNING:  'Makefile.defines_int.in' seems to ignore the --datarootdir setting
[fpm@facepalm]~/src/silc% make
...
make[7]: Entering directory `/home/fpm/src/silc/apps/irssi/src/silc/core'
/bin/sh ../../../libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../.. -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -I../../.. -I../../../src -DSYSCONFDIR=\""/usr/etc"\" -I../../.. -I../../../src -I../../../src/core -I../../../src/fe-common/core -I../../../src/fe-common/silc -DSILC_PLUGIN -D_GNU_SOURCE -g -Wall -finline-functions -Wno-pointer-sign -O2 -D_REENTRANT -DHAVE_SILCDEFS_H -I. -I../../.. -I/home/fpm/src/silc -I/home/fpm/src/silc/lib/contrib -I/home/fpm/src/silc/lib/silccore -I/home/fpm/src/silc/lib/silccrypt -I/home/fpm/src/silc/lib/silcmath -I/home/fpm/src/silc/lib/silcutil -I/home/fpm/src/silc/lib/silcapputil -I/home/fpm/src/silc/lib/silcske -I/home/fpm/src/silc/lib/silcsftp -I/home/fpm/src/silc/lib/silcclient -I/home/fpm/src/silc/lib/silcasn1 -I/home/fpm/src/silc/lib/silcskr -I/home/fpm/src/silc/lib/silcvcard -I/home/fpm/src/silc/includes -I/home/fpm/src/silc/doc    -g -O2 -Wall -Wno-deprecated-declarations   -MT clientutil.lo -MD -MP -MF .deps/clientutil.Tpo -c -o clientutil.lo clientutil.c
mv -f .deps/clientutil.Tpo .deps/clientutil.Plo
mv: cannot stat`.deps/clientutil.Tpo': No such file or directory
make[7]: **\* [clientutil.lo] Error 1

**Comment by priikone** [comment]
On Wed, 14 May 2014, danhimalplanet wrote:

> after running
> git clone https://github.com/silc/silc
> autodist client
> automake --add-missing
> autodist client
> 
> [fpm@facepalm]~/src/silc% ./configure --prefix=/usr --with-silc-plugin  --without-silc-includes --enable-shared 1>/dev/null
> /bin/grep: no/silc.h: No such file or directory
> /bin/grep: no/silc.h: No such file or directory
> config.status: WARNING:  'apps/irssi/Makefile.defines_int.in' seems to ignore the --datarootdir setting
> config.status: WARNING:  'Makefile.defines_int.in' seems to ignore the --datarootdir setting
> [fpm@facepalm]~/src/silc%
> [fpm@facepalm]~/src/silc% ./configure --prefix=/usr --with-silc-plugin=/usr/lib64/irssi --without-silc-includes --enable-shared 1>/dev/null
> /bin/grep: no/silc.h: No such file or directory
> /bin/grep: no/silc.h: No such file or directory
> config.status: WARNING:  'apps/irssi/Makefile.defines_int.in' seems to ignore the --datarootdir setting
> config.status: WARNING:  'Makefile.defines_int.in' seems to ignore the --datarootdir setting
> [fpm@facepalm]~/src/silc% make 1>/dev/null
> mv: cannot stat `.deps/clientutil.Tpo': No such file or directory
> 
> Dunno.  If I give the same set of commands in my tree, it compiles without 
> issues.  Can you compile the silc-client tar package?

```
Pekka
```

**Comment by priikone** [comment]
Quick googling shows you might want to try give autoreconf -i command to fix the issue.  I've never personally had to run that.
