### ISSUE TITLE
README.MACOSX missing from silc-client tarball

### ISSUE THREAD

**Issue by estan** [silc/silc#3]
The 1.1.11 tarball has no README.MACOSX in the top-level directory, this leads to:

Making install in doc
make  install-data-hook
mkdir -p /home/estan/silc-client/share/doc/silc-client
/usr/bin/install -c -m 644 ../doc/FAQ /home/estan/silc-client/share/doc/silc-client/
/usr/bin/install -c -m 644 ../COPYING /home/estan/silc-client/share/doc/silc-client/
/usr/bin/install -c -m 644 ../ChangeLog /home/estan/silc-client/share/doc/silc-client/
/usr/bin/install -c -m 644 ../CREDITS /home/estan/silc-client/share/doc/silc-client/
/usr/bin/install -c -m 644 ../README /home/estan/silc-client/share/doc/silc-client/
/usr/bin/install -c -m 644 ../README.MACOSX /home/estan/silc-client/share/doc/silc-client/
install: ../README.MACOSX: No such file or directory

Since it's specified in doc/Makefile.am.

Not sure if README.MACOSX should be added to the tarball, or the install command removed.

**Comment by estan** [comment]
I just realized the same is true in the silc-toolkit tarball, although there it is which is README.PLUGIN which is not present (as well as ../lib/doc/*.gif which lib/Makefile.am tries to install).

**Comment by priikone** [comment]
Fixed in 4f6c970d4.  Thanks.
